#!/bin/bash

# (cd ..; icmbuild) || exit 1
# CMD="g++ -o driver -Wall -I../ driver.cc -L../tmp -lofoldstreambuf -L../../tmp/lib -lbobcat -s"

CMD="g++ -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib \
                                                    -lreadline -lbobcat -s"

# CMD="g++ -o driver -Wall *.cc -lbobcat -s"
# CMD="g++ -o driver -Wall *.cc ../*o -lreadline -s"

echo $CMD
$CMD
