-----------------------------8463851424774285061082711556
Content-Disposition: form-data; name="hidden"

hidval
-----------------------------8463851424774285061082711556
Content-Disposition: form-data; name="text"

some text
-----------------------------8463851424774285061082711556
Content-Disposition: form-data; name="password"


-----------------------------8463851424774285061082711556
Content-Disposition: form-data; name="c1"

one
-----------------------------8463851424774285061082711556
Content-Disposition: form-data; name="c1"

three
-----------------------------8463851424774285061082711556
Content-Disposition: form-data; name="radio"

1
-----------------------------8463851424774285061082711556
Content-Disposition: form-data; name="file"; filename="demo.pim"
Content-Type: application/octet-stream

#demo.im


string a =  "a/*" ;

-----------------------------8463851424774285061082711556
Content-Disposition: form-data; name="textarea"

Enter your text here
And over multitple rows is OK

-----------------------------8463851424774285061082711556
Content-Disposition: form-data; name="submit"

Submit Query
-----------------------------8463851424774285061082711556--

