
manpagesection(DISTRIBUTION FILES)
    itemization(
    itt(bobcat_CurVers_-x.dsc): detached signature;
    itt(bobcat_CurVers_-x.tar.gz): source archive;
    itt(bobcat_CurVers_-x_i386.changes): change log;
    itt(bobcat_CurVers_-x_i386.deb): debian package holding the
            libraries;
    itt(bobcat-dev__CurVers_-x_i386.deb): debian package holding the
            libraries, headers and manual pages;
    itt(http://sourceforge.net/projects/bobcat): public archive location;
COMMENT(
    itt(ftp://ftp.rug.nl/contrib/frank/software/linux/bobcat/): public archive
location.
    )
    )

manpagesection(BOBCAT)
    Bobcat is an acronym of `Brokken's Own Base Classes And Templates'.

manpagesection(COPYRIGHT)
    This is free software, distributed under the terms of the 
    Academic Free Licence.

manpageauthor()
    Frank B. Brokken (bf(f.b.brokken@rug.nl)).

