#!/bin/bash

CWD=`pwd`
cd ../bobcat
     build sf || exit 1
    build man || exit 1
    cp required /home/frank/git/bobcat/wip
cd $CWD

yodl2html index || exit 1

scp index.html ../bobcat/tmp/manhtml/*html \
    fbb,bobcat@web.sourceforge.net:htdocs/

rm index.html
