#!/bin/bash

CWD=`pwd`
cd ../bobcat
     build sourceforge || exit 1
    build man || exit 1
cd $CWD

yodl2html index || exit 1

scp index.html ../bobcat/tmp/manhtml/*html \
    fbb,bobcat@web.sourceforge.net:htdocs/

rm index.html
