#!/bin/sh
PROJECT=bobcat

cvsremove

cd bobcat

# When recreating to repair lintian/linda messages, uncomment the following
# two commands and rerun `distribution'
make/clean
make/man

export BOBCAT=minimal 
dpkg-buildpackage -mf.b.brokken@rug.nl  -rfakeroot 2>&1 | tee /tmp/$PROJECT 

cd ..

cvsrestore

echo LINTIAN ...
lintian -i *.changes 
echo LINDA ...
linda   -i *.changes
