#!/bin/bash
PROJECT=bobcat

[ -d ${PROJECT} ] || exit 1             # the $PROJECT dir must exist

cd  ${PROJECT}
[ -s VERSION ] || exit 1                # VERSION must exist in $PROJECT

. VERSION                               # load it
DISTRIBUTION=${PROJECT}-${VERSION}      # define the distribution's dir name

cd ..                                   # change the CVS dir name to the
mv ${PROJECT} ${DISTRIBUTION}           # distribution's dir name

if [ "$#" != "0" ]                      # any arg? make debian .orig file
then

                                        # create the .orig source tar
    tar czvf ${PROJECT}_${VERSION}.orig.tar.gz \
                --exclude=lintian\
                --exclude=.svn\
                --exclude=debian ${DISTRIBUTION}
else
    tar czvf ${PROJECT}_${VERSION}.tar.gz \
                --exclude=lintian\
                --exclude=.svn\
                --exclude=debian ${DISTRIBUTION}
    gpg -ba ${PROJECT}_${VERSION}.tar.gz
fi
                                        # change the distribution's dir name
mv ${DISTRIBUTION} ${PROJECT}           # back to the cvs's dir name



