#!/bin/bash

ln -sf ../configfile .
ln -sf ../configfile.ih .

case $1 in
    (b)
        rm configfile configfile.ih
        g++ -DBOBCAT --static --std=c++0x -I../../tmp -o driver driver.cc \
            -L../../tmp/lib  -lbobcat -s
    ;;
    (o)
        g++ --std=c++0x -o driver *.cc ../tmp/o/*.o -lbobcat -s
    ;;
    (c)
        g++ --std=c++0x -o driver *.cc -lbobcat -s
    ;;
    (*)
    echo $0 b links to bobcat built by 'build libraries all'
    echo $0 o links to the files in ../tmp/o
    echo $0 c links to the files in the current dir only
    rm -f driver
    ;;
esac

rm -f configfile configfile.ih




