#!/bin/bash

tput clear

LIBS=" -lbobcat"
GPP="g++ --std=c++0x"

# WHEN LINKING TO A STATIC LIBRARY DON'T FORGET TO LINK AGAINST 
# ssl (-lssl)

# CMD="$GPP -o driver -Wall -I../ driver.cc -L../tmp ${LIBS} -lbigint  -s"
# CMD="$GPP -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib ${LIBS} -s"
# CMD="$GPP -o driver -Wall -I../ driver.cc -L../tmp ${LIBS} -s"
# CMD="$GPP -o driver -Wall driver.cc ../*.o ../../pf_*/*.o ${LIBS} -s"

CMD="$GPP -o driver -Wall *.cc ${LIBS} -s"

echo $CMD
$CMD || exit 1

echo Ready...
driver 4

