#!/bin/bash

ln -sf ../argconfig .
ln -sf ../argconfig.ih .

case $1 in
    (b)
        g++ --std=c++0x -o driver *.cc -lbobcat -s
    ;;
    (o)
        g++ -o driver *.cc -L../tmp -largconfig -lbobcat -s
    ;;
    (c)
        g++ -o driver *.cc -lbobcat -s
    ;;
    (*)
    echo $0 b links to the installed bobcat library
    echo $0 o links to the files in ../tmp/o
    echo $0 c links to the files in the current dir only
    ;;
esac
