#!/bin/bash

#CMD="g++ --std=c++0x -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib \
#                                                     -lbobcat -s"

CMD="g++ --std=c++0x -o driver -Wall driver.cc ../*.o -lbobcat -s"


echo $CMD
$CMD
