#!/bin/sh

# Argument 1: optional prefix path to installation paths for non-dev
# e.g., debian/libbobcat1 argument 2: optional prefix path to intstallation
# path for -dev, e.g. debian/libbobcat1-dev

. make/parameters

req()
{
    echo "$*"
    $* || exit 1
}

reqeval()
{
    echo "$*"
    eval "$*" || exit 1
}

reqzip()
{
    DEST=$1
    shift

    for x in $*
    do
        reqeval "gzip -9 < $x > $DEST/`basename $x`.gz"
    done
}


echo "  install the libraries"
req mkdir -p $1$LIB
req cp -d tmp/lib/*so.* $1$LIB

req mkdir -p $2$LIB
req cp -d tmp/lib/*.{a,so} $2$LIB

echo "  install lintian overrides for the -dev package"
req mkdir -p $2$LINTIAN
req cp lintian/* $2$LINTIAN

echo "  install the headers"
req mkdir -p $2$INC
req cp tmp/bobcat/* $2$INC

echo "  install the manual pages"
req mkdir -p $2$MAN/man3
reqzip $2$MAN/man3 tmp/man/man3/*

req mkdir -p $2$MAN/man7
reqeval "gzip -9 < tmp/man/man7/bobcat.7 > $2$MAN/man7/bobcat.7.gz"

echo "  install the html versions of the man-pages"
req mkdir -p $2/$DOCDEV/man
reqzip $2$DOCDEV/man tmp/manhtml/* 
req ln -sf bobcat.7.html $2$DOCDEV/man/index.html
req cp documentation/man/bobcat.jpg $2$DOCDEV/man/

echo "  remaining documentation"
reqzip $2$DOCDEV README README.class-setup TODO 
req cp -r documentation/examples $2$DOCDEV

[ "$DOC" == "" ] && exit 0

req mkdir -p $1$DOC
reqzip $1$DOC README 





