#!/bin/sh

. INSTALL.cf

req()
{
    echo "$*"
    $* || exit 1
}

make/special

mkdir -p tmp/man/man3 tmp/man/man7 tmp/manhtml

req cd documentation/man

for yo in `find ./ -name '*.yo' -and -not -name 'bobcat.yo' -printf "%f\n"`
do
    [ -e man-stamp -a man-stamp -nt $yo ] && continue
    BASE=${yo%\.[^\.]*}
    req yodl2man  --no-warnings -o ../../tmp/man/man3/$BASE.3bobcat $yo
    req yodl2html  --no-warnings -o ../../tmp/manhtml/$BASE.3.html $yo
done

[ -e man-stamp -a man-stamp -nt bobcat.yo ] && exit 0

req yodl2man  --no-warnings -o ../../tmp/man/man7/bobcat.7 bobcat.yo
req yodl2html  --no-warnings -o ../../tmp/manhtml/bobcat.html bobcat.yo

touch man-stamp


