#!/bin/sh

CWD=`pwd`
cd ../bobcat
    build man || exit 1
cd $CWD

yodl2html index || exit 1

scp *html ../bobcat/tmp/manhtml/*html \
	fbb,bobcat@shell.sourceforge.net:/home/groups/b/bo/bobcat/htdocs
