#!/bin/sh

# ln -s .. bobcat
# 
# g++ -I. --std=c++14 -O2 -Wall -o driver driver.cc -lssl -lbobcat \
#     -L../tmp -ldecryptbuf
# 
# rm bobcat

# echo g++ --std=c++14 -O2 -Wall -o driver driver.cc -lbobcat 
# g++ --std=c++14 -O2 -Wall -o driver driver.cc -lbobcat 

tput clear

LIBS=" -lbobcat -lcrypto"
GPP="g++ --std=c++14"

#   Using the standard bobcat library
#CMD="$GPP -o driver -Wall *.cc ${LIBS} -s"

#   Using the library in ../tmp/
CMD="$GPP -o driver -Wall *.cc -L../tmp -ldecryptbuf ${LIBS} -s"

echo ${CMD}
${CMD}

