#!/bin/bash

LIBS="-lreadline -lbobcat"

#CMD="g++ --std=c++0x -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib \
#                                                    ${LIBS} -s"

CMD="g++ --std=c++0x -o driver -Wall driver.cc ${LIBS} -s"

echo $CMD
$CMD
