#!/bin/bash

tput clear

GPP="g++ --std=c++0x"

# WHEN LINKING TO A STATIC LIBRARY DON'T FORGET TO LINK AGAINST ssl (-lssl)

# CMD="$GPP -o driver -Wall -I../ driver.cc -L../tmp -lbigint -lbobcat -s"
CMD="$GPP -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib -lbobcat -s"
# CMD="$GPP -o driver -Wall -I../ driver.cc -L../tmp -lbigint -lbobcat -s"

# CMD="$GPP -o driver -Wall *.cc -lbobcat -s"

echo $CMD
$CMD || exit 1

echo Ready...
driver

