#!/bin/bash

tput clear

GPP="g++ --std=c++14"

CMD="$GPP -o driver -Wall -I../ driver.cc -L../tmp -lhostent -lbobcat -s"
# CMD="$GPP -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib -lbobcat -s"
# CMD="$GPP -o driver -Wall *.cc -lbobcat -s"

echo $CMD
$CMD || exit 1

echo Ready...
driver
