#!/bin/bash

case $1 in
    (b)
        g++ --std=c++0x -o driver *.cc -lbobcat -s
    ;;
    (a)
        g++ --std=c++0x -o driver *.cc -L../tmp -largconfig -lbobcat -s
    ;;
    (*)
    echo $0 a links to the files in the current dir, ../tmp/libargconfig
    echo and bobcat
    echo $0 b links to the installed bobcat library
    ;;
esac
