#!/bin/bash

rm -f driver

case $1 in
    (tmp)
        echo "g++ -c driver.cc"
        g++ --std=c++11 -I../../tmp -c driver.cc || exit 1
        g++ -o driver driver.o -L../../tmp/lib -lbobcat
    ;;
    (lib)
        echo "g++ -c driver.cc"
        g++ --std=c++11 -I../../tmp -o driver.o -c driver.cc || exit 1
        g++ -o driver driver.o -lbobcat
    ;;
    (*)
    echo "
Usage: 
    build tmp   - build the driver using the shared library created in
                  ../../tmp/lib
    build lib   - build the driver using the shared bobcat library installed
                  in the standard location for shared libs
"
    exit 1
    ;;
esac
