#!/bin/sh

# ln -s .. bobcat
# 
# g++ -I. --std=c++14 -O2 -Wall -o driver driver.cc -lssl -lbobcat \
#     -L../../ohexstreambuf/tmp -L../tmp -lhmacbuf   -lohexstreambuf
# 
# rm bobcat

tput clear

LIBS=" -lbobcat -lcrypto"
GPP="g++ --std=c++14"

#   Using the standard bobcat library
#CMD="$GPP -o driver -Wall *.cc ${LIBS} -s"

#   Using the library in ../tmp/
CMD="$GPP -o driver -Wall *.cc -L../tmp -lhmacbuf ${LIBS} -s"

echo ${CMD}
${CMD}
