#include "main.hh"

void header(ostream &out)
{
    out << 
"#ifndef INCLUDED_BOBCAT_LC_\n"
"#define INCLUDED_BOBCAT_LC_\n"
"\n"
"// This header file was generated by the bobcatlcgen program which is\n"
"// distributed with the Bobcat source archive under the directory\n"
"// 'bobcat/lc/lcgen'. The binary program itself is probably available as\n"
"// /usr/bin/bobcatlcgen.\n"
"// The distributed Local Context header allows for the definition and\n"
"// declaration of a local context struct having at most 10 fields. If\n"
"// more fields are required (e.g., 15), then generate your own local\n"
"// context struct header file using the command:\n"
"//\n"
"//      bobcatlcgen 15 your-header\n"
"//\n"
"// and #include \"your-header\" rather than <bobcat/lc> in your sources.\n"
"\n"
"namespace FBB\n"
"{\n"
"\n"
"struct Unspecified\n"
"{};\n"
"\n";

}




