#!/bin/sh

# ln -s .. bobcat
#g++ -I. --std=c++0x -O2 -Wall -o driver driver.cc -lssl -lbobcat \
#      -L../../ohexstreambuf/tmp -L../tmp -ldigestbuf  -lohexstreambuf
# rm bobcat


tput clear

LIBS=" -lbobcat"
GPP="g++ --std=c++0x"

CMD="$GPP -o driver -Wall *.cc ${LIBS} -s"

echo ${CMD}
${CMD}

