#!/bin/sh

case $1 in
    (1)
        g++-4.4 --std=c++0x -c -Wall driver.cc
        g++-4.4 -o driver *.o ../*.o -lbobcat  -lX11
    ;;
    (2)
        g++ -o driver -Wall -I../../tmp *.cc -lX11 -L../../tmp/lib -lbobcat
    ;;
    (3)
        g++ -o driver -Wall *.cc -lbobcat -lX11
    ;;
    (*)
        echo "
Provide arg 1, 2 or 3:
    1: link to .o files in ..
    2: link to a created bobcat in ../../tmp/lib
    3: link to installed bobcat
"
    ;;
esac
