#!/bin/bash

# ln -s .. bobcat
# ln -s ../ohexstreambuf/ohexstreambuf bobcat
# 
# g++ -I. --std=c++0x -O2 -Wall -o driver driver.cc -lssl -lbobcat \
#       -L../../ohexstreambuf/tmp -L../tmp -lencryptbuf -lohexstreambuf
# 
# rm bobcat/ohexstreambuf bobcat

# echo g++ --std=c++0x -O2 -Wall -o driver driver.cc -lbobcat 
# g++ --std=c++0x -O2 -Wall -o driver driver.cc -lbobcat 

echo g++ -I. --std=c++0x -O2 -Wall -o driver driver.cc -L../tmp -lencryptbuf \
        -lssl -lbobcat

g++ -I. --std=c++0x -O2 -Wall -o driver driver.cc -L../tmp -lencryptbuf \
        -lssl -lbobcat

