#!/bin/bash

# uncomment the following to use the library created in ../tmp/lib
#INC="-I../../tmp"
#LIB="-L../../tmp/lib"

for x in *.cc 
do
    NAME=`echo $x | sed 's/\..*//'`
    if [ ! -s ${NAME}.o ]
    then
        echo "g++ -c $x"
        g++ ${INC} -o ${NAME}.o -c $x || exit 1
    fi
done

rm -f driver

g++ -o driver *.o ${LIB} -lbobcat
