#!/bin/bash

#CMD="g++ --std=c++14 -o driver -Wall -I../../tmp driver.cc -L../../tmp/lib \
#                                                     -lbobcat -s"

# CMD="g++ --std=c++14 -o driver -Wall driver.cc ../*.o -lbobcat -s"
CMD="g++ --std=c++14 -o driver -Wall driver.cc -lbobcat -s"


echo $CMD
$CMD
