.TH "Bobcat" "7" "2005-2006" "libbobcat1-dev_1\&.10\&.0-x\&.tar\&.gz" "C++ Classes"

.PP 
.SH "NAME"
Bobcat \- Overview of classes in the Bobcat library
.PP 
.SH "DESCRIPTION"
The classes of the \fBBobcat\fP library may be used after including 
\fBbobcat/classname\fP in sources\&. 
.PP 
All classes and other elements are defined in the \fBFBB\fP namespace\&.
.PP 
The following classes are available:
.PP 
\fBFBB::Arg\fP: Interfaces the command line arguments, allowing for
short- and long options\&. The class is implemented as a \fISingleton\fP\&.
.br 
(Manpage: \fBman -e bobcat arg\fP)
.PP 
\fBFBB::A2x\fP: Ascii-to-x conversions of any type supporting extractions
from \fBi[string]stream\fP objects\&. 
(Manpage: \fBman -e bobcat a2x\fP)
.PP 
\fBFBB::ClientSocket\fP: a socket for tcp-communication with a server\&.
.br 
(Manpage: \fBman -e bobcat clientsocket\fP)
.PP 
\fBFBB::CmdFinder\fP: Command-function associations\&.
.br 
(Manpage: \fBman -e bobcat cmdfinder\fP)
.PP 
\fBFBB::CmdFinderBase\fP: Base class for \fBCmdFinder\fP\&.
.br 
(Manpage: \fBman -e bobcat cmdfinderbase\fP)
.PP 
\fBFBB::columnWidth\fP: Manipulator class for the class \fBTable\fP\&.
.br 
(Manpage: \fBman -e bobcat columnwidth\fP)
.PP 
\fBFBB::ConfigFile\fP: Processing standard configuration files\&.
.br 
(Manpage: \fBman -e bobcat configfile\fP)
.PP 
\fBFBB::DateTime\fP: Manipulations with date and time values\&.
.br 
(Manpage: \fBman -e bobcat datetime\fP)
.PP 
\fBFBB::equalWidth\fP: Manipulator class for the class \fBTable\fP\&.
.br 
(Manpage: \fBman -e bobcat equalwidth\fP)
.PP 
\fBFBB::Errno\fP: Defines objects which may be thrown as an exception\&.
.br 
(Manpage: \fBman -e bobcat errno\fP)
.PP 
\fBFBB::Fork\fP: Defines \fBfork\fP(2) as part of a Template Algorithm Design
Pattern\&. 
.br 
(Manpage: \fBman -e bobcat fork\fP)
.PP 
\fBFBB::GetHostent\fP: Obtains \fBhostent\fP struct from hostname or
-address\&. 
.br 
(Manpage: \fBman -e bobcat gethostent\fP)
.PP 
\fBFBB::Glob\fP: Obtain a list of files matching a certain pattern\&.
.br 
(Manpage: \fBman -e bobcat glob\fP)
.PP 
\fBFBB::Hostname\fP: Derived from \fBHostent\fP, allows the initialization
from a \fBstd::string\fP, or from an \fBFBB::InetAddrress\fP\&. 
.br 
(Manpage: \fBman -e bobcat hostname\fP)
.PP 
\fBFBB::IFdStream\fP: stream extracting information from a device whose
file descriptor is available\&. 
.br 
(Manpage: \fBman -e bobcat ifdstream\fP)
.PP 
\fBFBB::IFdStreambuf\fP: Input stream buffer initialized by a file
descriptor\&.
.br 
(Manpage: \fBman -e bobcat ifdstreambuf\fP)
.PP 
\fBFBB::Indent\fP: Class and manipulators performing text indentation\&. 
.br 
(Manpage: \fBman -e bobcat indent\fP)
.PP 
\fBFBB::InetAddress\fP: Base class (no public constructor) for objects
representing an internet address as used with sockets\&. Contains address
and portnumbers\&. 
.br 
(Manpage: \fBman -e bobcat inetaddress\fP)
.PP 
\fBFBB::IOStream\fP: class combining \fBstd::istream\fP and \fBstd::ostream\fP
features\&. 
.br 
(Manpage: \fBman -e bobcat iostream\fP)
.PP 
\fBFBB::IOStreambuf\fP: \fBstd::streambuf\fP specialization allowing combined 
input and output operations\&. 
.br 
(Manpage: \fBman -e bobcat iostreambuf\fP)
.PP 
\fBFBB::IRandStream\fP: stream to extract random numbers from\&. 
.br 
(Manpage: \fBman -e bobcat irandstream\fP)
.PP 
\fBFBB::Hash\&.\&.\&.\fP: Various template classes implementing mapping containers
using hashing\&.
.br 
(Manpage: \fBman -e bobcat hash\fP)
.PP 
\fBFBB::Hostent\fP: Wrapper around the \fBhostent\fP struct\&. 
.br 
(Manpage: \fBman -e bobcat hostent\fP)
.PP 
\fBFBB::level\fP: Manipulator setting the log-level of \fBFBB::Log\fP
objects\&.
.br 
(Manpage: \fBman -e bobcat level\fP)
.PP 
\fBFBB::LocalClientSocket\fP: a Unix domain socket for 
tcp-communication with a Unix domain (local) server\&.
.br 
(Manpage: \fBman -e bobcat localclientsocket\fP)
.PP 
\fBFBB::LocalServerSocket\fP: defines a Unix domain socket to which
clients on the local host can connect\&.
.br 
(Manpage: \fBman -e bobcat localserversocket\fP)
.PP 
\fBFBB::LocalSocketBase\fP: Base class for \fBLocalClientSocket\fP and
\fBLocalServerSocket\fP\&. 
.br 
(Manpage: \fBman -e bobcat localsocketbase\fP)
.PP 
\fBFBB::Log\fP: \fBstd::ostream\fP handling log messages\&.
.br 
(Manpage: \fBman -e bobcat log\fP)
.PP 
\fBFBB::LogBuffer\fP: \fBstd::streambuf\fP handling log messages\&.
.br 
(Manpage: \fBman -e bobcat logbuffer\fP)
.PP 
\fBFBB::MailHeaders\fP: extracts mail headers from SMTP-email\&.
.br 
(Manpage: \fBman -e bobcat mailheaders\fP)
.PP 
\fBFBB::Milter\fP: interfaces the sendmail mail filter facilities\&.
.br 
(Manpage: \fBman -e bobcat milter\fP)
.PP 
\fBFBB::Msg\fP: Offers static member function and manipulators which may be
used for various types of messages\&.
.br 
(Manpage: \fBman -e bobcat msg\fP)
.PP 
\fBFBB::MultiStreambuf\fP: \fBstd::streambuf\fP specializations performing
insertions to multiple \fBstd::ostream\fP objects\&.
.br 
(Manpage: \fBman -e bobcat multistreambuf\fP)
.PP 
\fBFBB::OFdStream\fP: stream inserting information into a device whose
file descriptor is available\&. 
.br 
(Manpage: \fBman -e bobcat ofdstream\fP)
.PP 
\fBFBB::OFdStreambuf\fP: Output stream buffer initialized by a file
descriptor\&.
.br 
(Manpage: \fBman -e bobcat ofdstreambuf\fP)
.PP 
\fBFBB::OneKey\fP: Single keystroke input, not requiring `Return\&'\&.
.br 
(Manpage: \fBman -e bobcat onekey\fP)
.PP 
\fBFBB::Pattern\fP: Performs regular expression pattern matching\&.
.br 
(Manpage: \fBman -e bobcat pattern\fP)
.PP 
\fBFBB::Pipe\fP: Defines a system level pipe\&. 
.br 
(Manpage: \fBman -e bobcat pipe\fP)
.PP 
\fBFBB::Process\fP: Runs child processes, defining pipes between parents and
child processes\&. 
.br 
(Manpage: \fBman -e bobcat process\fP)
.PP 
\fBFBB::Randbuffer\fP: implements a \fBstreambuf\fP generating random 
numbers\&. 
.br 
(Manpage: \fBman -e bobcat randbuffer\fP)
.PP 
\fBFBB::Redirector\fP: Defines system level file redirection\&. 
.br 
(Manpage: \fBman -e bobcat redirector\fP)
.PP 
\fBFBB::RefCount\fP: Base class implementing reference counting\&. 
.br 
(Manpage: \fBman -e bobcat refcount\fP)
.PP 
\fBFBB::Selector\fP: Offers timed delays and multiple file I/O\&. 
.br 
(Manpage: \fBman -e bobcat selector\fP)
.PP 
\fBFBB::ServerSocket\fP: defines a socket to which clients can connect\&.
.br 
(Manpage: \fBman -e bobcat serversocket\fP)
.PP 
\fBFBB::SocketBase\fP: Base class for \fBClientSocket\fP and \fBServerSocket\fP\&.
.br 
(Manpage: \fBman -e bobcat socketbase\fP)
.PP 
\fBFBB::Stat\fP: Determines file characteristics\&.
.br 
(Manpage: \fBman -e bobcat stat\fP)
.PP 
\fBFBB::String\fP: Offers extended \fBstd::string\fP functionality\&.
.br 
(Manpage: \fBman -e bobcat string\fP)
.PP 
\fBFBB::Syslogbuf\fP: streambuf to
Buffer generating \fBsyslog\fP(3) messages\&. 
.br 
(Manpage: \fBman -e bobcat syslogbuf\fP)
.PP 
\fBFBB::SyslogStream\fP: stream to
Output stream inserting \fBsyslog\fP(3) messages\&. 
.br 
(Manpage: \fBman -e bobcat syslogbuf\fP)
.PP 
\fBFBB::Table\fP: Display tables row- or column-wise\&.
.br 
(Manpage: \fBman -e bobcat table\fP)
.PP 
\fBFBB::TableSpec\fP: Base class for the class \fBTable\fP\&.
.br 
(Manpage: \fBman -e bobcat tablespec\fP)
.PP 
\fBFBB::TableSupport\fP: Support class for the class \fBTable\fP\&.
.br 
(Manpage: \fBman -e bobcat tablesupport\fP)
.PP 
\fBFBB::User\fP: Determines the current user\&'s parameters from
\fI/etc/passwd\fP\&.
.br 
(Manpage: \fBman -e bobcat user\fP)
.PP 
\fBFBB::Wrap1\fP: Configurable wrapper function object template class
to be used with generic algorithms\&.
.br 
(Manpage: \fBman -e bobcat wrap\fP)
.PP 
\fBFBB::Wrap1c\fP: Configurable unary wrapper function object template class
using context information to be used with generic algorithms\&.
.br 
(Manpage: \fBman -e bobcat wrap1c\fP)
.PP 
\fBFBB::Wrap2\fP: Configurable binary wrapper function object template class
to be used with generic algorithms\&.
.br 
(Manpage: \fBman -e bobcat wrap2\fP)
.PP 
\fBFBB::Wrap2c\fP: Configurable binary wrapper function object template class
using context information to be used with generic algorithms\&.  
.br 
(Manpage: \fBman -e bobcat wrap2c\fP)
.PP 
\fBFBB::Xpointer\fP: sets and retrieves the X-windows pointer\&.
.br 
(Manpage: \fBman -e bobcat xpointer\fP)
.PP 
\fBFBB::X2a\fP: x-to-Ascii conversions of any type supporting insertions
from \fBo[string]stream\fP objects\&.
.br 
(Manpage: \fBman -e bobcat x2a\fP)
.PP 
.SH "FILES"
.IP o 
\fB/usr/include/bobcat/<classname>\fP:
.br 
.IP o 
\fB/usr/lib/libbobcat\&.*\fP:
.br 
(shared, static libraries)

.PP 
.SH "SEE ALSO"
The individual \fBbobcat/<class>\fP header files, with man-pages accessible
using \fIman -e bobcat class\fP (all lowercase names)
.PP 
.SH "BUGS"
No Reported Bugs\&.
.PP 
.SH "DISTRIBUTION FILES"
.IP o 
\fIbobcat_1\&.10\&.0-x\&.dsc\fP: detached signature;
.IP o 
\fIbobcat_1\&.10\&.0-x\&.tar\&.gz\fP: source archive;
.IP o 
\fIbobcat_1\&.10\&.0-x_i386\&.changes\fP: change log;
.IP o 
\fIlibbobcat1_1\&.10\&.0-x_i386\&.deb\fP: debian package holding the
libraries;
.IP o 
\fIlibbobcat1-dev_1\&.10\&.0-x_i386\&.deb\fP: debian package holding the
libraries, headers and manual pages;
.IP o 
\fIhttp://sourceforge\&.net/projects/bobcat\fP: public archive location;

.PP 
.SH "BOBCAT"
Bobcat is an acronym of `Brokken\&'s Own Base Classes And Templates\&'\&.
.PP 
.SH "COPYRIGHT"
This is free software, distributed under the terms of the 
Academic Free Licence\&.
.PP 
.SH "AUTHOR"
Frank B\&. Brokken (\fBf\&.b\&.brokken@rug\&.nl\fP)\&.
.PP 
