#!/bin/sh

req()
{
    echo "$*"
    $* || exit 1
}

req rm -rf "debian/bobcat" "debian/bobcat-dev" "build-stamp" "configure-stamp" \
           "debian/substvars"


if [ "$BOBCAT" = "minimal" ] 
then
    echo "
    WARNING: PERFORMED MINIMAL CLEANUP
    "
    exit 0
fi

req rm -rf "tmp" "release.yo" "o" "*/o"
req cd documentation
req rm -rf "man/*html" "man/*{3,7}*" "bobcat" "man/man-stamp"

