#!/bin/sh

. `pwd`/VERSION
. `pwd`/INSTALL.cf

req()
{
    echo "$*"
    $* || exit 1
}

if [ ! -e release.yo -o VERSION -nt release.yo ] 
then
    echo "
SUBST(_CurVers_)($VERSION)
SUBST(_CurYrs_)($YEARS)
" > release.yo
fi

