#!/bin/sh

ln -sf ../process .
ln -sf ../process.ih .

case $1 in
    (o)
        g++ -o driver *.cc ../tmp/o/*.o -lbobcat -s
    ;;
    (c)
        g++ -o driver *.cc -lbobcat -s
    ;;
    (*)
    echo $0 o links to the files in ../tmp/o
    echo $0 c links to the files in the current dir only
    ;;
esac
