#!/bin/bash

ln -sf ../cidr .
ln -sf ../cidr.ih .

case $1 in
    (b)
        rm cidr cidr.ih
        g++ -DBOBCAT --std=c++14 -I../../tmp -o driver driver.cc \
            -lbobcat -L../../tmp/lib -s
    ;;
    (o)
        g++ --std=c++14 -o driver *.cc ../tmp/o/*.o -lbobcat -s
    ;;
    (c)
        g++ --std=c++14 -o driver *.cc -lbobcat -s
    ;;
    (*)
    echo $0 b links to bobcat built by 'build libraries all'
    echo $0 o links to the files in ../tmp/o
    echo $0 c links to the files in the current dir only
    rm -f driver
    ;;
esac

rm -f cidr cidr.ih
