#!/bin/sh

. INSTALL.cf

run()
{
    echo "$*"
    $* || exit 1
}

run mkdir -p $LIB $INC $MAN $DOC

for x in wrap1 wrap1c wrap2 wrap2c hash table ifdstream ofdstream
do
    run cp $x/$x ${INC}
done

NR=0
for x in    errno \
            msg \
            a2x\
            string\
            arg\
            x2a\
            pattern\
            redirector\
            pipe\
            ofdstreambuf\
            fork\
            selector\
            ifdstreambuf\
            configfile\
            user\
            datetime\
            glob\
            stat\
            tablespec\
            tablesupport\
            equalwidth\
            columnwidth\
            process\
            syslogbuf\
            syslogstream\
            logbuffer\
            log\
            level\
            hostent\
            gethostent\
            inetaddress\
            socketbase\
            clientsocket\
            serversocket\
            hostname
do
    run cd $x
    run cp $x ${INC}
    run mkdir -p o
    for src in *.cc
    do
        BASE=${src%\.[^\.]*}
        [ o/${NR}${BASE}.o -nt ${src} ] ||
            run g++ -I../${INC} -Wall -O3 -o  o/${NR}${BASE}.o -c ${src}
    done
    run cd ..
    let NR=${NR}+1
done

# [ -e libbisonc++.a ] || run ar rs libbisonc++.a o/*.o */o/*o
# run g++ -o ${BIN}/bisonc++ -lbisonc++ -L. -lbobcat -s
# 
# run cp -r share/* ${SKEL}
# 
# run cp COPYING ${DOC}
# 
# run cp -r documentation/examples ${DOC}/examples
# run cp -r documentation/man/calculator ${DOC}/man
# run cp -r documentation/{html,bison.ps.org} ${DOC}/bison-docs
# 
# 
# [ "$1" == "all" ] || exit 0
# 
# gcc -E VERSION.h | grep -v '#' | sed 's/\"//g' > release.yo
# 
# 
# run cd documentation/man
# 
# if [ ! -e bisonc++.1 -o \
#         bisonc++.yo -nt bisonc++.man -o \
#         ../../release.yo -nt bisonc++.1 ] 
# then
#     run yodl2man  -o bisonc++.1 bisonc++
#     run yodl2html -o bisonc++man.html bisonc++
# fi
# 
# gzip < bisonc++.1 > ${MAN}/usr/share/man/man1/bisonc++.1.gz
# run cp bisonc++man.html ${DOC}/man
# 
# 
# 
# run cd ../manual
# 
# [ -e verbinsert ] || run g++ -o verbinsert ../../contrib/verbinsert.cc -s
# 
# PATH=$PATH:`pwd`
# 
# [ -e invoking/usage ] || run ${BIN}/bisonc++ --help > invoking/usage
# 
# run yodl2html -l 3 bisonc++.yo
# 
# run cp *.html ${DOC}/manual
# 
# # run cd ../..


