#!/bin/sh

# ln -s .. bobcat
# 
# g++ -I. --std=c++14 -O2 -Wall -o driver driver.cc -lssl -lbobcat \
#     -L../../ohexstreambuf/tmp -L../tmp -lhmacbuf   -lohexstreambuf
# 
# rm bobcat

tput clear

LIBS=" -lbobcat"
GPP="g++ --std=c++14"

CMD="$GPP -o driver -Wall *.cc ${LIBS} -s"
echo ${CMD}
${CMD}
